spring:
  application:
    name: recipe-service

  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB_NAME:recipes-service}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    properties:
      client.dns.lookup: default
    consumer:
      group-id: recipe-service
    topics:
      recipes-topic: recipes-topic

server:
  port: 8080