spring:
  application:
    name: recipe-service

  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB_NAME:recipes-service}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Postgres
          format_sql: true